apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-nijima
spec:
  selector:
    matchLabels:
      app: nijima # has to match .spec.template.metadata.labels
  serviceName: "service-nijima"
  replicas: 2 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: nijima # has to match .spec.selector.matchLabels
    spec:
      hostIPC: true
      #hostNetwork: true conflict found: node(s) didn't have free ports for the requested pod ports
      securityContext:
        runAsUser: 1000
      terminationGracePeriodSeconds: 10
      containers:  
      - name: makoto
        image: "naythan/nijima:test"
        imagePullPolicy: Always
        livenessProbe:
            exec:
              command:
              - touch
              - /tmp/healthy
        readinessProbe:
          exec:
            command:
            - touch
            - /tmp/healthy
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          capabilities:
            add: ["NET_ADMIN", "SYS_TIME", "SYS_ADMIN"]
        ports:
          - containerPort: 47984
            protocol: TCP
          - containerPort: 47985
            protocol: TCP
          - containerPort: 47986
            protocol: TCP
          - containerPort: 47987
            protocol: TCP
          - containerPort: 47988
            protocol: TCP
          - containerPort: 47989
            protocol: TCP
          - containerPort: 47990
            protocol: TCP
          - containerPort: 48010
            protocol: TCP
          - containerPort: 47998
            protocol: UDP
          - containerPort: 47999
            protocol: UDP
          - containerPort: 48000
            protocol: UDP
          - containerPort: 50000
            protocol: TCP
          - containerPort: 60000
            protocol: TCP
        #command: ["sleep", "120"]
        resources:
          limits:
            nvidia.com/gpu-4gb: "1"
            #nvidia.com/gpu: "1"
            #memory: 500m
            #cpu: '1'